### ISSUE TITLE
查询疫情政策时报错，查询风险地区时报错

### ISSUE THREAD

**Issue by SnowMoonSS** [Zeta-qixi/nonebot-plugin-covid19-news#15]
```
06-27 19:10:08 [SUCCESS] nonebot | ONEBOT V11 3011567668 | [message.group.normal]: Message -1248684487 from 123456789@[群:123456789] "上海疫情政策"
06-27 19:10:08 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False>
06-27 19:10:08 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> running complete
06-27 19:10:08 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 89, in _
    await send_msg(bot, event, city.policy)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 199, in send_msg
    await send_forward_msg_group(bot, event.group_id, [message])
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 188, in send_forward_msg_group
    await bot.call_api(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
 File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 131, in _call_api
    return handle_api_result(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/utils.py", line 47, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed status=failed, retcode=103, data=None, echo=37>
```
```
06-27 19:10:21 [SUCCESS] nonebot | ONEBOT V11 3011567668 | [message.group.normal]: Message -1406449017 from 123456789@[群:123456789] "上海风险地区"
06-27 19:10:21 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False>
06-27 19:10:21 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> running complete
06-27 19:10:21 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 101, in _
    await send_msg(bot, event, city.poi_list)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 199, in send_msg
    await send_forward_msg_group(bot, event.group_id, [message])
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 188, in send_forward_msg_group
    await bot.call_api(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 131, in _call_api
    return handle_api_result(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/utils.py", line 47, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed status=failed, retcode=103, data=None, echo=38>
```

**Comment by Zeta-qixi** [comment]
最新版本测试上海相关信息没问题，可能合并消息群发被风控，可以看看gocqhttp端日志，或者尝试私聊查询有没有问题。

**Comment by SnowMoonSS** [comment]
私聊只能查风险区域，防疫政策仍然报错，别的插件合并消息一切正常

**Comment by Zeta-qixi** [comment]
看看私聊防疫政策报错
试试其他地方防疫政策的合并消息，这边发现一些地区发送合并消息被风控 可能存在某些词导致。但私聊没有测试出问题。随便看看插件版本是多少。

**Comment by Zeta-qixi** [comment]
合并消息可能是内容存在敏感词原因 之后更新会以图片发送政策以及风险地区内容。

**Comment by Zeta-qixi** [comment]
测试了几次 发现群聊直接发文本消息不会失败，但合并消息存在部分地区的疫情信息发送失败。
如果不介意长文本刷屏可以修改`__init__.py`最后几段:
```
   # 注释198 - 200 三行代码
   # if event.message_type == 'group':
   #    await send_forward_msg_group(bot, event.group_id, [message])
   #else:
        await bot.send(event=event, message=message)
```

（近期会尝试能不能·为以图片形式发送信息

**Comment by Zeta-qixi** [comment]
cqhttp重启之后 之前合并消息发送失败的地区又能成功发送了，可以试试。

**Comment by Zeta-qixi** [comment]
图片形式推送已更新 应该可以有效解决这个问题

**Comment by SnowMoonSS** [comment]
设置了image，但仍然`08-01 10:35:37 [INFO] nonebot_plugin_covid19_news | 将以 Text形式发送合并消息`

**Comment by Zeta-qixi** [comment]
1.更新到最新版本.  0.5.3.3
2.有没有添加文字到相应位置 目前只能下载对应字体，或者重命名成对应名字（详细见readme 其他功能）

**Comment by SnowMoonSS** [comment]
加了字体以后，启动的时候提示以image形式发送，但是私聊还是文字，群聊还是报错
```
08-01 12:42:08 [SUCCESS] nonebot | ONEBOT V11 1234567890| [message.group.normal]: Message 2012586088 from 123456789@[群:123456789] "北京风险地区"
08-01 12:42:08 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False>
08-01 12:42:09 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> running complete
08-01 12:42:09 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/__init__.py", line 113, in _
    await send_msg(bot, event, get_city_poi_list(CITY_ID[city]))
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/uilts.py", line 79, in send_msg
    await send_forward_msg_group(bot, event.group_id, message)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot_plugin_covid19_news/uilts.py", line 40, in send_forward_msg_group
    await bot.call_api(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 131, in _call_api
    return handle_api_result(
  File "/home/newqqbot/.local/lib/python3.8/site-packages/nonebot/adapters/onebot/utils.py", line 47, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed status=failed, retcode=103, data=None, echo=9>
```

**Comment by Zeta-qixi** [comment]
nonebot端有没有什么报错？

**Comment by SnowMoonSS** [comment]
> nonebot端有没有什么报错？

这个日志就是nonebot控制台的报错

**Comment by Zeta-qixi** [comment]
> > nonebot端有没有什么报错？
> 
> 这个日志就是nonebot控制台的报错

（cqhttp 端，这个像api调用失败了

**Comment by SnowMoonSS** [comment]
啊这……确实。
这是mirai控制台的日志
```
2022-08-01 21:18:25 V/Bot.1234567890: [ABCDEFG(123456789)] ABC(123456789) -> 北京风险地区
2022-08-01 21:18:25 E/OneBot: 未知OneBot API: send_group_forward_msg
```
我这里用的是mirai+onebot-kotlin
是不是得换mirai-api-http……

**Comment by Zeta-qixi** [comment]
可以直接修改代码 `uilts.py`的`send_msg ()` 方法
```
async def send_msg(
        bot: Bot,
        event: Union[MessageEvent, int],
        message: Union[str, Message, List],
):
        if SEND_IMAGE:
            message = [text2image(msg) for msg in message]
        await bot.send(event=event, message=message)

```

**Comment by SnowMoonSS** [comment]
是我之前没注意到mirai控制台那边的报错，改了`send_msg()`之后文字也能正常发了
但是……
![image](https://user-images.githubusercontent.com/21017431/182527333-01ef9e7e-27e7-446f-ac7e-a105b6b03ead.png)

**Comment by Zeta-qixi** [comment]
修改了send_msg()的逻辑，现在 私聊也能发图片
