### ISSUE TITLE
查询任意地方防疫政策报错

### ISSUE THREAD

**Issue by okatu-loli** [Zeta-qixi/nonebot-plugin-covid19-news#19]
日志如下
07-31 18:57:48 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_covid19_news/__init__.py", line 106, in _
    await send_msg(bot, event, get_policy(CITY_ID[city]))
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_covid19_news/uilts.py", line 69, in send_msg
    message = [text2image(msg) for msg in message]
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_covid19_news/uilts.py", line 69, in <listcomp>
    message = [text2image(msg) for msg in message]
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_covid19_news/uilts.py", line 48, in text2image
    font = ImageFont.truetype(font=dirname(__file__)+"/font/MSYH.TTC", size = FONT_SIZE)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by Zeta-qixi** [comment]
已修复，现在默认还是发送文字，需要图片形式发送，参照`readme`修改配置。
