### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Passerby-D** [Zeta-qixi/nonebot-plugin-covid19-news#22]
虽然我知道大概率是我操作的问题,但我确实搞不明白哪里出问题了
就是不管输入什么城市的/城市+疫情,都会显示"查询的城市不存在或存在别名"
安装是用nb_cli装的

**Comment by Zeta-qixi** [comment]
是类似 `广州市疫情` 还是 `广州疫情` 这样的？

**Comment by Passerby-D** [comment]
后者格式
输入的是/南京疫情

**Comment by Zeta-qixi** [comment]
试一下用pip安装。
`pip install -U nonebot-plugin-covid19-news `

**Comment by Passerby-D** [comment]
好像还是不行

**Comment by Zeta-qixi** [comment]
先卸载再重新安装。
或者直接下载该项目到bot的插件目录（这样方便debug）

**Comment by Passerby-D** [comment]
重装了两遍依旧如此
主要是还没有报错，我就把covid19_news.handle()中的if city改成if True后的报错是（输入是/南京疫情）

08-21 02:46:55 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_covid19_news, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "f:\bot\Passerby_D\bot.py", line 83, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\__init__.py", line 261, in run      
    get_driver().run(*args, **kwargs)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\dependencies\__init__.py", line 92, 
in __call__
    return await self.call(**values)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_covid19_news\__init__.py", line 94, in _
    await covid19_news.send(message=f"{NewsBot.time}\n{city.main_info}")
AttributeError: 'NoneType' object has no attribute 'main_info'

感觉可能确实少点东西，但反复卸载重装也无果，不太懂，麻烦大佬了

**Comment by Zeta-qixi** [comment]
哦 你是不是用了命令前缀，查询的触发为了解决减少误触和过长地名触发不了的问题 用的是`endswith` 所以不需要命令前缀。 直接`南京疫情`这样。
如果使用习惯需要 在下次更新我会添加前缀判断。

**Comment by Passerby-D** [comment]
哦哦哦原来是这样，可以了可以了谢谢大佬，果然是我自己犯蠢了
