### ISSUE TITLE
疫情信息更新推送报错

### ISSUE THREAD

**Issue by NSQX13579** [Zeta-qixi/nonebot-plugin-covid19-news#32]
python=3.10.4  nonebot=2.0.0rc1
具体报错如下
11-18 09:30:00 [ERROR] apscheduler | Job "update (trigger: cron[minute='*/30', second='0'], next run at: 2022-11-18 10:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/home/bot/bot/bot.py", line 79, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot_plugin_covid19_news/__init__.py", line 193, in update
    await get_bot().send_private_msg(user_id= int(gid), message= '关注城市疫情变化\n' + city.main_info)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 116, in call_api
    raise exception
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(
  File "/usr/local/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed

**Comment by NSQX13579** [comment]
> 

直接查询没有问题，只有更新推送报错
data.json也无空字符

**Comment by Zeta-qixi** [comment]
那应该是`nonebot-plugin-apscheduler`这个依赖的问题，先试试更新这个依赖

**Comment by NSQX13579** [comment]
更新后依旧报错
![2DXN0R%P`8(U CMX_D%LONV](https://user-images.githubusercontent.com/102937666/202843380-0c786343-4831-4bfb-ac88-61384f231349.png)

**Comment by Zeta-qixi** [comment]
emmm  报错信息看应该是`nonebot-plugin-apscheduler`的问题 ，但我新建相同环境测试没有报错
```
nonebot-adapter-cqhttp      2.0.0b1
nonebot-adapter-onebot      2.1.5
nonebot-plugin-apscheduler  0.2.0
nonebot-plugin-covid19-news 0.6.3.1
nonebot2                    2.0.0rc1

python = 3.10.8
```
