### ISSUE TITLE
ValueError: There are no bots to get.

### ISSUE THREAD

**Issue by forchannot** [Zeta-qixi/nonebot-plugin-covid19-news#39]
12-08 00:30:00 [INFO] nonebot_plugin_covid19_news | [疫情数据更新]
12-08 00:30:01 [INFO] nonebot_plugin_covid19_news | [疫情数据更新]
12-08 00:30:01 [ERROR] apscheduler | Job "update (trigger: cron[minute='*/30', second='0'], next run at: 2022-12-08 01:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\fwq\LittlePaimon\bot.py", line 40, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_covid19_news\__init__.py", line 176, in update
    bot = get_bot()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\__init__.py", line 158, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.

**Comment by Zeta-qixi** [comment]
bot掉线了

**Comment by Zeta-qixi** [comment]
其他功能正常使用吗

**Comment by Zeta-qixi** [comment]
那应该是gocq断线之后会尝试重连，但刚好那段时间定时检查`get_bot()`获取不了bot的内容。
之后的更新再修复这个bug。
